### ISSUE TITLE
✨[Feat] 재사용 가능한 TextField 영역 재사용 뷰로 만들기

### ISSUE THREAD

**Issue by hwangJi-dev** [hwangJi-dev/UXThinkBig_TextField#1]
### 💡 Issue
재사용 가능한 TextField 영역 재사용 뷰로 만들기

### ✅ To-Do
- [x] Reusable View 만들기
- [x] Reusable Class 만들기
- [x] Status에 따른 분기처리 (Checkbox, Timer)
