### ISSUE TITLE
✨[Feat] VerifyView 구현 - 휴대폰번호, 인증번호 UI

### ISSUE THREAD

**Issue by hwangJi-dev** [hwangJi-dev/UXThinkBig_TextField#3]
### 💡 issue
VerifyView 구현 - 휴대폰번호, 인증번호 UI

### ✅ To-Do
- [x] VerifyVC에서 ReusableView 불러오기 (휴대폰번호view, 인증번호view)
- [x] 각각 layout Constraint 잡아주기
- [x] Timer 구현
- [x] enter키 입력시 Notification 전달 -> 인증번호 view animation으로 생성
